// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrSvtQ-fzUqbD0jBe0E0Cbttru2b9KvOI',
    appId: '1:917815378759:web:e2dd4bd0ea54ec53a6c262',
    messagingSenderId: '917815378759',
    projectId: 'medical-c958f',
    authDomain: 'medical-c958f.firebaseapp.com',
    storageBucket: 'medical-c958f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ZjjFch5ZgCBPwf9sdTvQ4iWsYt46rJ0',
    appId: '1:917815378759:android:8796e6b5e56f47c3a6c262',
    messagingSenderId: '917815378759',
    projectId: 'medical-c958f',
    storageBucket: 'medical-c958f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeL5k0vKRUcqCHZ3BSzFjTMXJc7c9cn-0',
    appId: '1:917815378759:ios:1b86b859bb15de7ca6c262',
    messagingSenderId: '917815378759',
    projectId: 'medical-c958f',
    storageBucket: 'medical-c958f.appspot.com',
    iosBundleId: 'com.testing.medical',
  );
}
